apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka-producer
  name: kafka-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-producer
  template:
    metadata:
      labels:
        app: kafka-producer
    spec:
      containers:
        - name: kafka-producer
          image: docker.io/roniepaolo/twitch-chat:latest
          env:
            - name: TWITCH_CHANNELS
              value: roniepaolo
            - name: KAFKA_TOPIC
              value: twitch_chat
            - name: KAFKA_PRODUCER_BOOTSTRAP_SERVERS
              value: prod-cluster-kafka-bootstrap:9092
            - name: KAFKA_PRODUCER_ACKS
              value: all
            - name: KAFKA_PRODUCER_KEY_SERIALIZER
              value: io.confluent.kafka.serializers.KafkaAvroSerializer
            - name: KAFKA_PRODUCER_VALUE_SERIALIZER
              value: io.confluent.kafka.serializers.KafkaAvroSerializer
            - name: KAFKA_PRODUCER_SCHEMA_REGISTRY_URL
              value: http://schemaregistry-0-internal:8081
