apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: twitch-chat
  labels:
    strimzi.io/cluster: prod-cluster
spec:
  topicName: twitch_chat
  partitions: 1
  replicas: 1
  config:
    retention.ms: 2629800000
    segment.bytes: 107374182
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: camel-telegram
  labels:
    strimzi.io/cluster: prod-cluster
spec:
  topicName: camel_telegram
  partitions: 1
  replicas: 1
  config:
    retention.ms: 2629800000
    segment.bytes: 107374182
